//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osnovna_Sredstva_Glavna.Modules.OsnovnaSredstva.OsnovnoSredstvo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AktivacijaSredstva
    {
        public int INT { get; set; }
        public Nullable<int> OsnovnoId { get; set; }
        public System.DateTime DatumAktivacije { get; set; }
    }
}
