//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osnovna_Sredstva_Glavna.Modules.OsnovnaSredstva.OsnovnoSredstvo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AktivacijaSredstva> AktivacijaSredstva { get; set; }
    
        public virtual int sp_AktivacijaSredstva(Nullable<int> osnovnoId, Nullable<System.DateTime> datumAktivacije)
        {
            var osnovnoIdParameter = osnovnoId.HasValue ?
                new ObjectParameter("OsnovnoId", osnovnoId) :
                new ObjectParameter("OsnovnoId", typeof(int));
    
            var datumAktivacijeParameter = datumAktivacije.HasValue ?
                new ObjectParameter("DatumAktivacije", datumAktivacije) :
                new ObjectParameter("DatumAktivacije", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AktivacijaSredstva", osnovnoIdParameter, datumAktivacijeParameter);
        }
    }
}
