//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osnovna_Sredstva_Glavna.Modules.OsnovnaSredstva.Izvjesca
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Osnovna_Sredstva_GlavnaEntities : DbContext
    {
        public Osnovna_Sredstva_GlavnaEntities()
            : base("name=Osnovna_Sredstva_GlavnaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_KarticaSredstvaPojedinacno_Result> sp_KarticaSredstvaPojedinacno(Nullable<int> osnovnoId)
        {
            var osnovnoIdParameter = osnovnoId.HasValue ?
                new ObjectParameter("OsnovnoId", osnovnoId) :
                new ObjectParameter("OsnovnoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KarticaSredstvaPojedinacno_Result>("sp_KarticaSredstvaPojedinacno", osnovnoIdParameter);
        }
    
        public virtual int sp_ObracunAmortizacije(Nullable<int> obracunID)
        {
            var obracunIDParameter = obracunID.HasValue ?
                new ObjectParameter("ObracunID", obracunID) :
                new ObjectParameter("ObracunID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ObracunAmortizacije", obracunIDParameter);
        }
    }
}
